### ISSUE TITLE
'rcpress dev' fail. see detail:

### ISSUE THREAD

**Issue by mem5626** [YvesCoding/antdsite#10]
```bash
 FAIL  Module build failed (from /usr/local/lib/node_modules/@rcpress/cli/node_modules/babel-loader/lib/index.js):
SyntaxError: /usr/local/lib/node_modules/@rcpress/cli/node_modules/antd/package.json: Unexpected token, expected ";" (2:9)

  1 | {
> 2 |   "_from": "antd@latest",
    |          ^
  3 |   "_id": "antd@3.25.3",
  4 |   "_inBundle": false,
  5 |   "_integrity": "sha1-KEy/g89atsJt/7YGZXbyAupgr1A=",
    at Object.raise (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:6975:17)
    at Object.unexpected (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:8368:16)
    at Object.semicolon (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:8350:40)
    at Object.parseExpressionStatement (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11191:10)
    at Object.parseStatementContent (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:10790:19)
    at Object.parseStatement (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:10656:17)
    at Object.parseBlockOrModuleBlockBody (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11232:25)
    at Object.parseBlockBody (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11219:10)
    at Object.parseBlock (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11203:10)
    at Object.parseStatementContent (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:10732:21)
    at Object.parseStatement (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:10656:17)
    at Object.parseBlockOrModuleBlockBody (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11232:25)
    at Object.parseBlockBody (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:11219:10)
    at Object.parseTopLevel (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:10587:10)
    at Object.parse (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:12097:10)
    at parse (/usr/local/lib/node_modules/@rcpress/cli/node_modules/@babel/parser/lib/index.js:12148:38)

```

**Comment by mem5626** [comment]
I just found the solution after refering to [this page.](https://www.cnblogs.com/wangyinqian/p/11548886.html)
In `packages/@rcpress/webpack/src/createSPAConfig.js`, line 121
Change:
```js
  .test(/\.(jsx?)|(tsx?)$/)
```
into:
```js
  .test(/(\.jsx?|\.tsx?)$/)
```
After this modification, run `rcpress dev`, and it started succefully!

**Comment by wangyi7099** [comment]
确实很有道理， 我改一下再发布！ 谢谢！

**Comment by wangyi7099** [comment]
0.1.8
